# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.3'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
    customEndpoint: 'ciq'

- script: npm run build
  name: build
  displayName: "Run the build"

- script: npm install electron-packager

- script: ls node_modules\electron-packager

# Copy the finsemble-seed files to the publish location based on PR or version (if master)

# Modify the manifest file 

# Modify manifest location to match the publish location

- script: npm run makeInstaller:prod
  name: makeInstaller
  displayName: "Make a production installer"

# Publish the installer